### ISSUE TITLE
ReadTheDocs failing due to issue with conda?

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/fpga-interchange-schema#63]
```
Collecting package metadata: ...working... done
Solving environment: ...working... done
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Ran pip subprocess with arguments:
[u'/home/docs/checkouts/readthedocs.org/user_builds/fpga-interchange-schema/conda/latest/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/docs/checkouts/readthedocs.org/user_builds/fpga-interchange-schema/checkouts/latest/docs/tmpSDWH6s.requirements.txt']
Pip subprocess output:

Pip subprocess error:
ERROR: Exception:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/fpga-interchange-schema/conda/latest/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fpga-interchange-schema/conda/latest/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fpga-interchange-schema/conda/latest/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 286, in run
    reqs = self.get_requirements(args, options, finder, session)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fpga-interchange-schema/conda/latest/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 385, in get_requirements
    filename, finder=finder, options=options, session=session
  File "/home/docs/checkouts/readthedocs.org/user_builds/fpga-interchange-schema/conda/latest/lib/python3.7/site-packages/pip/_internal/req/req_file.py", line 135, in parse_requirements
    for parsed_line in parser.parse(filename, constraint):
  File "/home/docs/checkouts/readthedocs.org/user_builds/fpga-interchange-schema/conda/latest/lib/python3.7/site-packages/pip/_internal/req/req_file.py", line 319, in parse
    yield from self._parse_and_recurse(filename, constraint)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fpga-interchange-schema/conda/latest/lib/python3.7/site-packages/pip/_internal/req/req_file.py", line 348, in _parse_and_recurse
    yield from self._parse_and_recurse(req_path, nested_constraint)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fpga-interchange-schema/conda/latest/lib/python3.7/site-packages/pip/_internal/req/req_file.py", line 324, in _parse_and_recurse
    for line in self._parse_file(filename, constraint):
  File "/home/docs/checkouts/readthedocs.org/user_builds/fpga-interchange-schema/conda/latest/lib/python3.7/site-packages/pip/_internal/req/req_file.py", line 353, in _parse_file
    _, content = get_file_content(filename, self._session)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fpga-interchange-schema/conda/latest/lib/python3.7/site-packages/pip/_internal/req/req_file.py", line 518, in get_file_content
    resp = session.get(url)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fpga-interchange-schema/conda/latest/lib/python3.7/site-packages/pip/_vendor/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fpga-interchange-schema/conda/latest/lib/python3.7/site-packages/pip/_internal/network/session.py", line 454, in request
    return super().request(method, url, *args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fpga-interchange-schema/conda/latest/lib/python3.7/site-packages/pip/_vendor/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fpga-interchange-schema/conda/latest/lib/python3.7/site-packages/pip/_vendor/requests/sessions.py", line 697, in send
    r.content
  File "/home/docs/checkouts/readthedocs.org/user_builds/fpga-interchange-schema/conda/latest/lib/python3.7/site-packages/pip/_vendor/requests/models.py", line 836, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/home/docs/checkouts/readthedocs.org/user_builds/fpga-interchange-schema/conda/latest/lib/python3.7/site-packages/pip/_vendor/requests/models.py", line 769, in generate
    chunk = self.raw.read(chunk_size)
AttributeError: 'FileNotFoundError' object has no attribute 'read'
CondaEnvException: Pip failed
```

**Comment by mithro** [comment]
@kgugala / @acomodi - This was happening in other locations as well IIRC?
